CREATE TABLE USER_INFO (
    UNIQ_ID INT AUTO_INCREMENT,
    USERNAME VARCHAR(200),
    FULLNAME VARCHAR(200),
    EMAIL_USER VARCHAR(120),
	USER_PASSWORD VARCHAR(30)
    PRIMARY KEY(UNIQ_ID)
);
